# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install libpcap-dev
      run: sudo apt install -y libpcap-dev

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.2

    - name: Build
      run: go build -v ./...

    - name: List dir for debug
      run: ls -lha

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: linux
        path: prometheus-networkscan

  build-win:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install libpcap-dev
      run: sudo apt install -y libpcap-dev

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.2

    - name: Build
      run: GOOS=windows GOARCH=amd64 go build -v ./...

    - name: List dir for debug
      run: ls -lha

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: windows
        path: prometheus-networkscan.exe